# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_rx_fifo/mac_rx_fifo.xci
# IP: The module: 'mac_rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_rx_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_rx_fifo/mac_rx_fifo.xci
# IP: The module: 'mac_rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
