# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.runs/synth_1/Switch.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-106759-mlyue/incrSyn
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbv484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.cache/wt [current_project]
set_property parent.project_path /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/blk_mem_18x400/mem_table.coe
read_verilog -library xil_defaultlib {
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/CRC_check.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/LLC_top.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/MAC_rx_ctl.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/MAC_rx_ctl_top.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/MAC_top.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/MAC_tx_ctl.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/MDIO.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/MMU.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/arbiter.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/arbiter_rx.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/cache.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/clock_ctl.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/crc_10.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/ctl_center.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/gmii_to_rgmii/gmii_to_rgmii.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/mac_addr.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/queue.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/reg_ctl.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/gmii_to_rgmii/rgmii_rx.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/gmii_to_rgmii/rgmii_tx.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/rx_ctl_center.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/rx_fifo_top.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/LLC_layer/tx_ctl_center.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/new/MAC_layer/tx_fifo_top.v
  /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/Switch.v
}
read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mem_64x192/mem_64x192.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mem_64x192/mem_64x192_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/fifo_24x32/fifo_24x32.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/fifo_24x32/fifo_24x32.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/fifo_24x32/fifo_24x32_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/blk_mem_64x1000/blk_mem_64x1000.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/blk_mem_64x1000/blk_mem_64x1000_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/pll_mac/pll_mac.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac_board.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_ctl_fifo_18x16/mac_ctl_fifo_18x16.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_ctl_fifo_18x16/mac_ctl_fifo_18x16.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_ctl_fifo_18x16/mac_ctl_fifo_18x16_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_ctl_fifo_18x16/mac_ctl_fifo_18x16_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_rx_fifo/mac_rx_fifo.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_rx_fifo/mac_rx_fifo_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_tx_fifo/mac_tx_fifo.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo/mac_tx_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo/mac_tx_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo/mac_tx_fifo_ooc.xdc]

read_ip -quiet /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/blk_mem_18x400/blk_mem_18x400.xci
set_property used_in_implementation false [get_files -all /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/blk_mem_18x400/blk_mem_18x400_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/constrs_1/new/test1.xdc
set_property used_in_implementation false [get_files /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/constrs_1/new/test1.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/utils_1/imports/synth_1/MAC_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Switch -part xc7a200tfbv484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Switch.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Switch_utilization_synth.rpt -pb Switch_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
