# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048.xci
# IP: The module: 'mac_tx_fifo_64x256_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_tx_fifo_64x256_8x2048'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_tx_fifo_64x256_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_tx_fifo_64x256_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048.xci
# IP: The module: 'mac_tx_fifo_64x256_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_tx_fifo_64x256_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_tx_fifo_64x256_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_tx_fifo_64x256_8x2048/mac_tx_fifo_64x256_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_tx_fifo_64x256_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
