# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/pll_mac/pll_mac.xci
# IP: The module: 'pll_mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mac'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/pll_mac/pll_mac.xci
# IP: The module: 'pll_mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/pll_mac/pll_mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
