# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M.xci
# IP: The module: 'mac_clk_10_25_125M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_clk_10_25_125M'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_clk_10_25_125M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_clk_10_25_125M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.srcs/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M.xci
# IP: The module: 'mac_clk_10_25_125M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_clk_10_25_125M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_clk_10_25_125M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/Switch/vivado_proj/swtich.gen/sources_1/ip/mac_clk_10_25_125M/mac_clk_10_25_125M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_clk_10_25_125M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
